In [22]:
import sys
import csv
import os
import numpy as np
import scipy.io as sio
from scipy.spatial import distance

a = sio.loadmat('/media/thaovu/DATA/NCKH/NUS_WID_Low_Level_Features/test_ind.mat')
test_ind = a["M"]
test_ind = test_ind
a = sio.loadmat('/media/thaovu/DATA/NCKH/NUS_WID_Low_Level_Features/train_ind.mat')
train_ind = a["M"]
train_ind = train_ind

#a = sio.loadmat('/media/thaovu/DATA/NCKH/BIG DATA Multi features learning for image annotation/All_labels.mat')
#All_labels = a["All_labels"]
#X_labels = All_labels[train_ind,:]
#Y_labels = All_labels[test_ind,:]
X_labels = np.zeros((2400,12))
for i in range(12):
        X_labels[(i*200):((i*200)+200),i] = 1
        
Y_labels = np.zeros((1200,12))
for i in range(12):
        Y_labels[(i*100):((i*100)+100),i] = 1

########## top 100 BOW ##############
a = sio.loadmat('/media/thaovu/DATA/NCKH/NUS_WID_Low_Level_Features/BOW_int.mat')
BoW = a["BoW_int"]

Y_BOW = BoW[test_ind,:]
Y_BOW = Y_BOW.reshape(1200,500)
X_BOW = BoW[train_ind,:]
X_BOW = X_BOW.reshape(2400,500)

Dis = distance.cdist(Y_BOW, X_BOW, 'cityblock')

sort_ind = np.argsort(Dis)
BOW_index_top100 = sort_ind[:,0:100]

############### top 100 CH ############
a = sio.loadmat('/media/thaovu/DATA/NCKH/NUS_WID_Low_Level_Features/Nor_CH.mat')
CH = a["Normalized_CH"]

Y_CH = CH[test_ind,:]
Y_CH = Y_CH.reshape(1200,64)
X_CH = CH[train_ind,:]
X_CH = X_CH.reshape(2400,64)

Dis = distance.cdist(Y_CH, X_CH, 'cityblock')

sort_ind = np.argsort(Dis)
CH_index_top100 = sort_ind[:,0:100]

############### top 100 CM55 ############
a = sio.loadmat('/media/thaovu/DATA/NCKH/NUS_WID_Low_Level_Features/Nor_CM55.mat')
CM55 = a["Normalized_CM55"]

Y_CM55 = CM55[test_ind,:]
Y_CM55 = Y_CM55.reshape(1200,225)
X_CM55 = CM55[train_ind,:]
X_CM55 = X_CM55.reshape(2400,225)

Dis = distance.cdist(Y_CM55, X_CM55, 'cityblock')

sort_ind = np.argsort(Dis)
CM55_index_top100 = sort_ind[:,0:100]

############### top 100 CORR ############
a = sio.loadmat('/media/thaovu/DATA/NCKH/NUS_WID_Low_Level_Features/Nor_CORR.mat')
CORR = a["Normalized_CORR"]

Y_CORR = CORR[test_ind,:]
Y_CORR = Y_CORR.reshape(1200, 144)
X_CORR = CORR[train_ind,:]
X_CORR =X_CORR.reshape(2400, 144)

Dis = distance.cdist(Y_CORR, X_CORR, 'cityblock')

sort_ind = np.argsort(Dis)
CORR_index_top100 = sort_ind[:,0:100]

############### top 100 EDH ############
a = sio.loadmat('/media/thaovu/DATA/NCKH/NUS_WID_Low_Level_Features/Nor_EDH.mat')
EDH = a["Normalized_EDH"]

Y_EDH = EDH[test_ind,:]
Y_EDH = Y_EDH.reshape(1200, 73)
X_EDH = EDH[train_ind,:]
X_EDH = X_EDH.reshape(2400, 73)

Dis = distance.cdist(Y_EDH, X_EDH, 'cityblock')

sort_ind = np.argsort(Dis)
EDH_index_top100 = sort_ind[:,0:100]

############### top 100 WT ############
a = sio.loadmat('/media/thaovu/DATA/NCKH/NUS_WID_Low_Level_Features/Nor_WT.mat')
WT = a["Normalized_WT"]

Y_WT = WT[test_ind,:]
Y_WT = Y_WT.reshape(1200, 128)
X_WT = WT[train_ind,:]
X_WT = X_WT.reshape(2400, 128)

Dis = distance.cdist(Y_WT, X_WT, 'cityblock')

sort_ind = np.argsort(Dis)
WT_index_top100 = sort_ind[:,0:100]

################# gan nhan #############
n_class = 12
num_concept_per_imgs = 1
K_NN = 50
labels_predict = np.zeros(shape=(1,n_class))
for i in range(1200):
    BOW_100KNN_concepts = X_labels[BOW_index_top100[i,],]
    CH_100KNN_concepts = X_labels[CH_index_top100[i,],]
    CM55_100KNN_concepts = X_labels[CM55_index_top100[i,],]
    CORR_100KNN_concepts = X_labels[CORR_index_top100[i,],]
    EDH_100KNN_concepts = X_labels[EDH_index_top100[i,],]
    WT_100KNN_concepts = X_labels[WT_index_top100[i,],]

    img_labels = np.zeros(shape=(1,n_class))

    inter_joint_list = np.concatenate((BOW_100KNN_concepts[0:K_NN,], CH_100KNN_concepts[0:K_NN,], CM55_100KNN_concepts[0:K_NN,], CORR_100KNN_concepts[0:K_NN,], EDH_100KNN_concepts[0:K_NN,],WT_100KNN_concepts[0:K_NN,]), axis=0)
    inter_joint_list = inter_joint_list.reshape(300,12)

    out_labels = np.sum(inter_joint_list, axis = 0)
    ind_sort = np.argsort(out_labels)[::-1]
    result_index = ind_sort[0:num_concept_per_imgs]
    print (result_index)
    img_labels [0,result_index] = 1
    labels_predict = np.concatenate((labels_predict, img_labels),axis=0)


[2]
[11]
[0]
[4]
[0]
[0]
[0]
[7]
[0]
[1]
[0]
[0]
[0]
[10]
[4]
[0]
[1]
[7]
[0]
[0]
[0]
[0]
[7]
[0]
[0]
[1]
[0]
[0]
[0]
[7]
[0]
[6]
[0]
[0]
[0]
[0]
[4]
[4]
[0]
[10]
[0]
[0]
[0]
[1]
[0]
[0]
[7]
[6]
[8]
[0]
[7]
[0]
[7]
[0]
[0]
[0]
[0]
[8]
[0]
[0]
[0]
[7]
[0]
[0]
[0]
[3]
[0]
[0]
[6]
[6]
[3]
[0]
[0]
[0]
[9]
[0]
[0]
[0]
[0]
[10]
[7]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[3]
[3]
[7]
[4]
[7]
[0]
[0]
[7]
[1]
[4]
[1]
[9]
[10]
[10]
[9]
[9]
[7]
[7]
[7]
[3]
[1]
[3]
[2]
[0]
[7]
[4]
[1]
[10]
[10]
[4]
[0]
[6]
[10]
[1]
[0]
[7]
[1]
[1]
[1]
[4]
[3]
[1]
[1]
[1]
[4]
[1]
[5]
[4]
[0]
[4]
[9]
[7]
[1]
[3]
[3]
[0]
[0]
[1]
[3]
[1]
[1]
[7]
[0]
[0]
[0]
[10]
[3]
[10]
[0]
[0]
[11]
[7]
[1]
[1]
[7]
[4]
[4]
[1]
[7]
[0]
[1]
[4]
[6]
[2]
[0]
[4]
[0]
[11]
[7]
[6]
[4]
[1]
[4]
[4]
[1]
[0]
[4]
[4]
[4]
[9]
[10]
[2]
[11]
[1]
[1]
[3]
[1]
[10]
[2]
[7]
[4]
[8]
[6]
[1]
[6]
[8]
[0]
[0]
[7]
[7]
[11]
[0]
[8]
[7]
[7]
[2]
[2]
[6]
[1]
[3]
[2]
[0]
[8]
[0]
[6]
[4]
[8]
[4]
[6]
[10]
[0]
[0]
[7]
[4]
[10]
[10]
[3]
[2]
[7]
[7]
[0]
[0]
[5]
[4]


In [23]:
labels_predict = labels_predict[1:1201,:]

In [24]:
(a,b)=labels_predict.shape

In [25]:
a

1200

In [26]:
for i in range(a):
    for j in range(b):    
        if labels_predict[i,j] == 0:
            labels_predict[i,j] = 2

In [27]:
labels_predict

array([[ 2.,  2.,  1., ...,  2.,  2.,  2.],
       [ 2.,  2.,  2., ...,  2.,  2.,  1.],
       [ 1.,  2.,  2., ...,  2.,  2.,  2.],
       ..., 
       [ 2.,  2.,  2., ...,  2.,  2.,  2.],
       [ 2.,  2.,  2., ...,  2.,  2.,  2.],
       [ 2.,  2.,  2., ...,  2.,  2.,  2.]])

In [28]:
Y_labels

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [29]:

for i in range(a):
    for j in range(b):    
        labels_predict[i,j] = labels_predict[i,j] - Y_labels[i,j]

In [30]:
labels_predict

array([[ 1.,  2.,  1., ...,  2.,  2.,  2.],
       [ 1.,  2.,  2., ...,  2.,  2.,  1.],
       [ 0.,  2.,  2., ...,  2.,  2.,  2.],
       ..., 
       [ 2.,  2.,  2., ...,  2.,  2.,  1.],
       [ 2.,  2.,  2., ...,  2.,  2.,  1.],
       [ 2.,  2.,  2., ...,  2.,  2.,  1.]])

In [31]:
k=0
for i in range(a):
    for j in range(b):
        if labels_predict[i,j] == 0:
            print (i,j)
            k = k + 1

2 0
4 0
5 0
6 0
8 0
10 0
11 0
12 0
15 0
18 0
19 0
20 0
21 0
23 0
24 0
26 0
27 0
28 0
30 0
32 0
33 0
34 0
35 0
38 0
40 0
41 0
42 0
44 0
45 0
49 0
51 0
53 0
54 0
55 0
56 0
58 0
59 0
60 0
62 0
63 0
64 0
66 0
67 0
71 0
72 0
73 0
75 0
76 0
77 0
78 0
81 0
82 0
83 0
84 0
85 0
86 0
87 0
88 0
89 0
90 0
96 0
97 0
101 1
111 1
117 1
124 1
127 1
128 1
129 1
132 1
133 1
134 1
136 1
143 1
148 1
150 1
151 1
163 1
164 1
168 1
171 1
182 1
185 1
194 1
195 1
197 1
216 2
217 2
221 2
238 2
249 2
254 2
256 2
267 2
276 2
281 2
285 2
287 2
296 2
300 3
303 3
307 3
310 3
313 3
318 3
319 3
320 3
322 3
325 3
327 3
329 3
333 3
334 3
335 3
340 3
342 3
343 3
344 3
345 3
349 3
350 3
351 3
354 3
356 3
357 3
361 3
364 3
365 3
366 3
368 3
372 3
375 3
379 3
381 3
383 3
385 3
390 3
392 3
395 3
397 3
398 3
400 4
402 4
403 4
406 4
409 4
415 4
425 4
426 4
427 4
429 4
430 4
432 4
436 4
438 4
439 4
440 4
444 4
448 4
450 4
454 4
455 4
456 4
457 4
459 4
460 4
461 4
463 4
469 4
470 4
471 4
478 4
480 4
484 4
487 4
493 4
494 4
495 4

In [35]:
k

392

In [34]:
acc = k / 1200

0.32666666666666666